/**
 * Bot command definitions (for the Telegram command menu) and help text.
 */
export const COMMANDS: { command: string; description: string }[] = [
  { command: "start", description: "Welcome, menu & status panel" },
  { command: "menu", description: "Show the menu keyboard" },
  { command: "projects", description: "Projects: list / search <q> / open <path> / new <name>" },
  { command: "sessions", description: "List/resume sessions (active first) \u00b7 /sessions <q>" },
  { command: "active", description: "Sessions running now on the PC" },
  { command: "running", description: "Sessions this chat controls \u2014 switch between them" },
  { command: "killall", description: "Kill all active sessions on the PC" },
  { command: "mcp", description: "Inspect & toggle MCP servers \u00b7 health-check" },
  { command: "models", description: "List live models reported by Codex" },
  { command: "agents", description: "List live Codex collaboration modes" },
  { command: "skills", description: "List live enabled Codex skills" },
  { command: "tasks", description: "Manage scheduled tasks" },
  { command: "newtask", description: "Create a scheduled task" },
  { command: "history", description: "Show recent conversation history" },
  { command: "new", description: "Start a fresh session here" },
  { command: "status", description: "Current session, project & queue" },
  { command: "usage", description: "Account & context usage" },
  { command: "btw", description: "Run ASAP (now if idle, else next): /btw <text>" },
  { command: "flush", description: "Send queued follow-ups now" },
  { command: "queue", description: "Show queued follow-ups" },
  { command: "cancel", description: "Stop the current turn" },
  { command: "unwatch", description: "Stop following a live session" },
  { command: "model", description: "Switch model: /model <id>" },
  { command: "restart", description: "Restart the Codex agent" },
  { command: "reauth", description: "Log in to Codex (ChatGPT / API key / import)" },
  { command: "accounts", description: "Switch between saved Codex accounts" },
  { command: "help", description: "Show help" },
];

export const HELP_TEXT = [
  "\u{1F916} Codex Telegram Bot",
  "Drive Codex CLI from your phone \u2014 projects, resume, live sessions, diffs.",
  "",
  "HOW IT WORKS",
  "\u2022 Just send a message to chat with Codex in the current project.",
  "\u2022 While Codex is working, anything you send is queued and runs",
  "  automatically when the current turn finishes.",
  "",
  "COMMANDS",
  "/projects \u2014 choose which folder Codex works in",
  "/sessions \u2014 resume one of your recent Codex sessions",
  "/active \u2014 attach to a session currently running on the PC",
  "/history \u2014 show the latest messages of the current session",
  "/new \u2014 start a brand-new session in the current project",
  "/btw <text> \u2014 run it now if idle, otherwise right after the current task",
  "/flush \u2014 run queued follow-ups immediately",
  "/cancel \u2014 stop the current turn",
  "/status \u2014 show session, project and queue size",
  "/reauth \u2014 log in to Codex (ChatGPT, API key, or import an existing login)",
  "/accounts \u2014 switch between saved Codex accounts",
  "/models \u00b7 /agents \u00b7 /skills \u2014 inspect live Codex capabilities",
].join("\n");
