/**
 * Bot command definitions (for the Telegram command menu) and help text.
 */
export const COMMANDS: { command: string; description: string }[] = [
  { command: "start", description: "Начало работы, меню и статус" },
  { command: "menu", description: "Открыть меню" },
  { command: "projects", description: "Проекты: список, поиск, открыть или создать" },
  { command: "sessions", description: "Список и продолжение сеансов" },
  { command: "active", description: "Сеансы, запущенные на компьютере" },
  { command: "running", description: "Сеансы, которыми управляет этот чат" },
  { command: "killall", description: "Остановить все активные сеансы" },
  { command: "mcp", description: "Серверы MCP и проверка связи" },
  { command: "models", description: "Список моделей Codex" },
  { command: "agents", description: "Режимы совместной работы Codex" },
  { command: "skills", description: "Включённые навыки Codex" },
  { command: "tasks", description: "Управление задачами по расписанию" },
  { command: "newtask", description: "Создать задачу по расписанию" },
  { command: "history", description: "Недавняя история переписки" },
  { command: "new", description: "Начать новый сеанс" },
  { command: "status", description: "Текущий сеанс, проект и очередь" },
  { command: "usage", description: "Использование аккаунта и контекста" },
  { command: "btw", description: "Выполнить при первой возможности: /btw <текст>" },
  { command: "flush", description: "Немедленно выполнить сообщения из очереди" },
  { command: "queue", description: "Показать очередь сообщений" },
  { command: "cancel", description: "Остановить текущую задачу" },
  { command: "unwatch", description: "Перестать следить за активным сеансом" },
  { command: "model", description: "Сменить модель: /model <название>" },
  { command: "restart", description: "Перезапустить Codex" },
  { command: "reauth", description: "Войти в Codex: ChatGPT, ключ API или импорт" },
  { command: "accounts", description: "Переключить сохранённый аккаунт Codex" },
  { command: "help", description: "Справка" },
];

export const HELP_TEXT = [
  "\u{1F916} Telegram-бот Codex",
  "Управляйте Codex с телефона: проекты, сеансы, задачи и история.",
  "",
  "КАК ЭТО РАБОТАЕТ",
  "\u2022 Отправьте сообщение, чтобы обратиться к Codex в текущем проекте.",
  "\u2022 Пока Codex занят, новые сообщения попадут в очередь и выполнятся",
  "  автоматически после завершения текущей задачи.",
  "",
  "КОМАНДЫ",
  "/projects \u2014 выбрать папку для работы Codex",
  "/sessions \u2014 продолжить один из недавних сеансов Codex",
  "/active \u2014 подключиться к сеансу, запущенному на компьютере",
  "/history \u2014 показать последние сообщения текущего сеанса",
  "/new \u2014 начать новый сеанс в текущем проекте",
  "/btw <текст> \u2014 выполнить сейчас, если бот свободен, иначе после текущей задачи",
  "/flush \u2014 немедленно выполнить сообщения из очереди",
  "/cancel \u2014 остановить текущую задачу",
  "/status \u2014 показать сеанс, проект и очередь",
  "/reauth \u2014 войти в Codex через ChatGPT, ключ API или существующий аккаунт",
  "/accounts \u2014 переключить сохранённый аккаунт Codex",
  "/models \u00b7 /agents \u00b7 /skills \u2014 список моделей, режимов и навыков Codex",
].join("\n");
